postgres:
  image: postgres:9.4.5
  environment:
    POSTGRES_USER: mobydock
    POSTGRES_PASSWORD: yourpassword
  ports:
    - '5432:5432'
  volumes:
    - ~/.docker-volumes/mobydock/postgresql/data:/var/lib/postgresql/data

redis:
  image: redis:3.0
  ports:
    - '6379:6379'
  volumes:
    - ~/.docker-volumes/mobydock/redis/data:/data
  entrypoint:
    - redis-server
    - --appendonly yes

mobydock:
  build: .
  environment:
    LOG_LEVEL: info
  command: /usr/lib/jvm/java-8-openjdk-amd64/bin/java -jar target/sparkexample-jar-with-dependencies.jar
  links:
    - postgres
    - redis
  ports:
    - '4567:4567'
