vk:
  client:
    clientId: ${VK_API_KEY}
    clientSecret: ${VK_API_SECRET}
    accessTokenUri: https://oauth.vk.com/access_token
    userAuthorizationUri: https://oauth.vk.com/authorize
    clientAuthenticationScheme: form
    scope:
     - email
     - profile
  resource:
    userInfoUri: https://api.vk.com/method/users.get?fields=photo_100

google:
  client:
    clientId: ${GOOGLE_API_KEY}
    clientSecret: ${GOOGLE_API_SECRET}
    accessTokenUri: https://www.googleapis.com/oauth2/v4/token
    userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
    clientAuthenticationScheme: form
    scope:
     - email
     - profile
  resource:
    userInfoUri: https://www.googleapis.com/userinfo/v2/me


linkedin:
  client:
    clientId: ${LD_API_KEY}
    clientSecret: ${LD_API_SECRET}
    accessTokenUri: https://www.linkedin.com/oauth/v2/accessToken
    userAuthorizationUri: https://www.linkedin.com/oauth/v2/authorization
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://api.linkedin.com/v1/people/~:(id,picture-url,first-name,last-name,email-address)?format=json

github:
  client:
    clientId: ${GITHUB_API_KEY}
    clientSecret: ${GITHUB_API_SECRET}
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    clientAuthenticationScheme: form
    scope:
     - user:email
  resource:
    userInfoUri: https://api.github.com/user

facebook:
  client:
    clientId: ${FB_API_KEY}
    clientSecret: ${FB_API_SECRET}
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
    scope:
     - public_profile
     - email
  resource:
    userInfoUri: https://graph.facebook.com/me?fields=first_name,last_name,email,picture

