linkedin:
  client:
    clientId: ${LD_API_KEY}
    clientSecret: ${LD_API_SECRET}
    accessTokenUri: https://www.linkedin.com/oauth/v2/accessToken
    userAuthorizationUri: https://www.linkedin.com/oauth/v2/authorization
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://api.linkedin.com/v1/people/~:(id,picture-url,first-name,last-name,email-address)?format=json

github:
  client:
    clientId: ${GITHUB_API_KEY}
    clientSecret: ${GITHUB_API_SECRET}
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    clientAuthenticationScheme: form
    scope:
     - user:email
  resource:
    userInfoUri: https://api.github.com/user

facebook:
  client:
    clientId: ${FB_API_KEY}
    clientSecret: ${FB_API_SECRET}
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
    scope:
     - public_profile
     - email
  resource:
    userInfoUri: https://graph.facebook.com/me?fields=first_name,last_name,email,picture

